create extension if not exists pgcrypto;
create table if not exists public.guest_reception_guests(id uuid primary key default gen_random_uuid(),guest_name text not null,address text,city text,state text,zip text,phone text,email text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists guest_reception_guests_phone_idx on public.guest_reception_guests(phone); create index if not exists guest_reception_guests_email_idx on public.guest_reception_guests(email);
create table if not exists public.guest_reception_visits(id uuid primary key default gen_random_uuid(),guest_id uuid not null references public.guest_reception_guests(id) on delete cascade,visit_date date not null,visit_number integer not null default 1,entry_source text not null default 'digital',created_at timestamptz not null default now());
create table if not exists public.guest_reception_outreach(id uuid primary key default gen_random_uuid(),guest_id uuid not null unique references public.guest_reception_guests(id) on delete cascade,outreach_person text,phone_outreach_date date,outreach_result text,next_follow_up_date date,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.guest_reception_inventory(id uuid primary key default gen_random_uuid(),item_name text not null,category text,quantity integer not null default 0,minimum_quantity integer not null default 0,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.guest_reception_inventory_transactions(id uuid primary key default gen_random_uuid(),inventory_item_id uuid not null references public.guest_reception_inventory(id) on delete cascade,transaction_type text not null,quantity integer not null,previous_quantity integer not null,new_quantity integer not null,notes text,transaction_date timestamptz not null default now());
create table if not exists public.guest_reception_imports(id uuid primary key default gen_random_uuid(),filename text not null,import_date timestamptz not null default now(),rows_processed integer not null default 0,new_guests integer not null default 0,returning_visits integer not null default 0,skipped_records integer not null default 0,failed_records integer not null default 0,status text not null default 'complete');
insert into public.guest_reception_inventory(item_name,category,quantity,minimum_quantity) select * from (values ('Welcome Bags','Welcome Items',32,20),('Guest Cards','Guest Materials',50,25),('Brochures','Guest Materials',50,20)) as s(item_name,category,quantity,minimum_quantity) where not exists(select 1 from public.guest_reception_inventory);
-- Apply the same RLS/policy approach already used by the existing DLC browser-based Supabase tables before production use.
