import {useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from './supabase.js';
import './GuestReception.css';

const today=()=>new Date().toISOString().slice(0,10);
const blank=()=>({guest_name:'',address:'',city:'Memphis',state:'TN',zip:'',phone:'',email:'',visit_date:today(),outreach_person:'',phone_outreach_date:'',notes:''});

export default function GuestReceptionApp({onHome}){
 const [page,setPage]=useState('dashboard'),[guests,setGuests]=useState([]),[visits,setVisits]=useState([]),[outreach,setOutreach]=useState([]),[inventory,setInventory]=useState([]),[people,setPeople]=useState([]),[form,setForm]=useState(blank()),[msg,setMsg]=useState(''),[selected,setSelected]=useState(null),[follow,setFollow]=useState({}),[search,setSearch]=useState(''),[newPerson,setNewPerson]=useState(''),[newItem,setNewItem]=useState({item_name:'',category:'Guest Materials',quantity:0,minimum_quantity:10}),[editItem,setEditItem]=useState(null);

 const load=useCallback(async()=>{
  const [g,v,o,i,p]=await Promise.all([
   supabase.from('guest_reception_guests').select('*').order('created_at',{ascending:false}),
   supabase.from('guest_reception_visits').select('*').order('visit_date',{ascending:false}).order('created_at',{ascending:false}),
   supabase.from('guest_reception_outreach').select('*'),
   supabase.from('guest_reception_inventory').select('*').order('item_name'),
   supabase.from('guest_reception_outreach_people').select('*').order('name')
  ]);
  setGuests(g.data||[]);setVisits(v.data||[]);setOutreach(o.data||[]);setInventory(i.data||[]);setPeople(p.data||[]);
  if(g.error)setMsg('Guest Reception database tables are not ready yet.');
 },[]);
 useEffect(()=>{load()},[load]);

 const gm=useMemo(()=>Object.fromEntries(guests.map(g=>[g.id,g])),[guests]);
 const count=id=>visits.filter(v=>v.guest_id===id).length;
 const last=id=>visits.filter(v=>v.guest_id===id).sort((a,b)=>b.visit_date.localeCompare(a.visit_date))[0];
 const month=today().slice(0,7),mv=visits.filter(v=>v.visit_date?.startsWith(month));
 const awaiting=guests.filter(g=>!outreach.find(o=>o.guest_id===g.id)?.phone_outreach_date).length;
 const visitActionLabel=g=>{const n=count(g.id);return n===1?'Record 2nd Visit':n===2?'Record 3rd Visit':'Record Return Visit'};

 async function saveGuest(again=false){
  if(!form.guest_name.trim())return setMsg('Guest name is required.');
  let existing=null;
  if(form.phone||form.email){const q=[];if(form.phone)q.push(`phone.eq.${form.phone}`);if(form.email)q.push(`email.eq.${form.email}`);const r=await supabase.from('guest_reception_guests').select('*').or(q.join(',')).limit(1);existing=r.data?.[0];}
  let id=existing?.id;
  if(!id){const r=await supabase.from('guest_reception_guests').insert({guest_name:form.guest_name,address:form.address,city:form.city,state:form.state,zip:form.zip,phone:form.phone,email:form.email}).select().single();if(r.error)return setMsg('Could not save guest.');id=r.data.id;}
  await supabase.from('guest_reception_visits').insert({guest_id:id,visit_date:form.visit_date,visit_number:count(id)+1,entry_source:'digital'});
  if(form.outreach_person||form.phone_outreach_date||form.notes)await supabase.from('guest_reception_outreach').upsert({guest_id:id,outreach_person:form.outreach_person,phone_outreach_date:form.phone_outreach_date||null,notes:form.notes},{onConflict:'guest_id'});
  setMsg(existing?'Returning guest visit recorded.':'Guest saved.');setForm(blank());load();
 }
 async function newVisit(g){if(!g?.id)return;const n=count(g.id)+1;const r=await supabase.from('guest_reception_visits').insert({guest_id:g.id,visit_date:today(),visit_number:n,entry_source:'digital'});if(r.error)return setMsg('Could not record visit.');setMsg(`${g.guest_name}: ${n===2?'2nd':n===3?'3rd':`${n}th`} visit recorded.`);load();}
 async function deleteGuest(g){if(!confirm(`Delete ${g.guest_name} and all of this guest's visit/follow-up history?`))return;const r=await supabase.from('guest_reception_guests').delete().eq('id',g.id);if(r.error)return setMsg('Could not delete guest.');setMsg(`${g.guest_name} deleted.`);load();}

 function openFollow(g){const o=outreach.find(x=>x.guest_id===g.id);setSelected(g);setFollow(o||{guest_id:g.id,outreach_person:'',phone_outreach_date:'',outreach_result:'',next_follow_up_date:'',notes:''});}
 async function saveFollow(){await supabase.from('guest_reception_outreach').upsert({...follow,guest_id:selected.id,phone_outreach_date:follow.phone_outreach_date||null,next_follow_up_date:follow.next_follow_up_date||null},{onConflict:'guest_id'});setSelected(null);setMsg('Follow-up saved.');load();}
 async function addPerson(){const name=newPerson.trim();if(!name)return;const r=await supabase.from('guest_reception_outreach_people').insert({name});if(r.error)return setMsg(r.error.code==='23505'?'That outreach person already exists.':'Could not add outreach person.');setNewPerson('');load();}
 async function deletePerson(p){if(!confirm(`Remove ${p.name} from the outreach-person dropdown?`))return;const r=await supabase.from('guest_reception_outreach_people').delete().eq('id',p.id);if(r.error)return setMsg('Could not remove outreach person.');load();}

 async function addInventory(){if(!newItem.item_name.trim())return setMsg('Inventory item name is required.');const r=await supabase.from('guest_reception_inventory').insert({...newItem,item_name:newItem.item_name.trim(),quantity:Number(newItem.quantity)||0,minimum_quantity:Number(newItem.minimum_quantity)||0});if(r.error)return setMsg('Could not add inventory item.');setNewItem({item_name:'',category:'Guest Materials',quantity:0,minimum_quantity:10});setMsg('Inventory item added.');load();}
 function openInventoryEdit(i){setEditItem({...i,quantity:Number(i.quantity)||0,minimum_quantity:Number(i.minimum_quantity)||0});}
 async function saveInventoryEdit(){if(!editItem)return;const r=await supabase.from('guest_reception_inventory').update({item_name:editItem.item_name.trim(),category:editItem.category,quantity:Number(editItem.quantity)||0,minimum_quantity:Number(editItem.minimum_quantity)||0,updated_at:new Date().toISOString()}).eq('id',editItem.id);if(r.error)return setMsg(`Could not update ${editItem.item_name}.`);setMsg(`${editItem.item_name} updated.`);setEditItem(null);load();}
 async function deleteInventory(i){if(!confirm(`Delete ${i.item_name} from inventory?`))return;const r=await supabase.from('guest_reception_inventory').delete().eq('id',i.id);if(r.error)return setMsg('Could not delete inventory item. Confirm the inventory DELETE RLS policy is enabled.');setMsg(`${i.item_name} deleted.`);load();}

 async function importCSV(file){const text=await file.text(),lines=text.split(/\r?\n/).filter(Boolean),headers=lines[0].split(',').map(x=>x.replaceAll('"','').trim());let n=0;for(const line of lines.slice(1)){const vals=line.split(',').map(x=>x.replaceAll('"','').trim()),r=Object.fromEntries(headers.map((h,i)=>[h,vals[i]||''])),name=r['Guest Name']||r['Names']||r['Name'];if(!name)continue;let existing=null;const phone=r.Phone||'',email=r.Email||'';if(phone||email){const q=[];if(phone)q.push(`phone.eq.${phone}`);if(email)q.push(`email.eq.${email}`);const found=await supabase.from('guest_reception_guests').select('*').or(q.join(',')).limit(1);existing=found.data?.[0];}let id=existing?.id;if(!id){const ins=await supabase.from('guest_reception_guests').insert({guest_name:name,address:r.Address||'',city:r.City||'Memphis',state:r.State||'TN',zip:r.ZIP||'',phone,email}).select().single();if(!ins.data)continue;id=ins.data.id;}const c=visits.filter(v=>v.guest_id===id).length;await supabase.from('guest_reception_visits').insert({guest_id:id,visit_date:r['Visit Date']||today(),visit_number:c+1,entry_source:'csv_import'});n++;}setMsg(`${n} guest rows imported.`);load();}
 function exportCSV(){const rows=[['Guest Name','Address','City','State','ZIP','Phone','Email','Visit Date','Visit Number','Entry Source']];visits.forEach(v=>{const g=gm[v.guest_id]||{};rows.push([g.guest_name,g.address,g.city,g.state,g.zip,g.phone,g.email,v.visit_date,v.visit_number,v.entry_source])});const csv=rows.map(r=>r.map(x=>`"${String(x||'').replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='DLC_Guest_Reception.csv';a.click();}

 return <div className="gr-app"><header className="gr-header"><div className="gr-brand"><img src="/dlclogo.png" alt="Divine Life Church"/><div><strong>Guest Reception Team</strong><span>Divine Life Connect</span></div></div><button onClick={onHome}>← Divine Life Connect</button></header><main className="gr-main"><nav className="gr-nav">{[['dashboard','Dashboard'],['entry','Enter Guest'],['follow','Follow-Up'],['visits','Visits'],['inventory','Inventory'],['data','Data']].map(([k,l])=><button key={k} className={page===k?'active':''} onClick={()=>setPage(k)}>{l}</button>)}</nav>{msg&&<div className="gr-msg">{msg}<button onClick={()=>setMsg('')}>×</button></div>}

 {page==='dashboard'&&<><div className="gr-title"><small>GUEST RECEPTION TEAM</small><h1>Welcome. Let’s keep it simple.</h1><p>Capture guests, follow up, and keep the team ready.</p></div><div className="gr-metrics"><article><span>Guests This Month</span><strong>{mv.length}</strong></article><article><span>First-Time Guests</span><strong>{mv.filter(v=>v.visit_number===1).length}</strong></article><article><span>Awaiting Outreach</span><strong>{awaiting}</strong></article></div><div className="gr-actions"><button className="primary" onClick={()=>setPage('entry')}><b>+ Enter Guest</b><span>Quick individual entry</span></button><button onClick={()=>setPage('data')}><b>↑ Import Guest Cards</b><span>Monday / Tuesday CSV batch</span></button><button onClick={()=>setPage('follow')}><b>View Follow-Up</b><span>See who needs outreach</span></button></div><div className="gr-panel"><h2>Recent Guests</h2><table><thead><tr><th>Guest</th><th>Visits</th><th>Last Visit</th><th>Quick Action</th><th></th></tr></thead><tbody>{guests.slice(0,8).map(g=><tr key={g.id}><td><strong>{g.guest_name}</strong></td><td>{count(g.id)>=3?'3+':count(g.id)}</td><td>{last(g.id)?.visit_date||'—'}</td><td><button className="gr-mini gr-visit-btn" onClick={()=>newVisit(g)}>{visitActionLabel(g)}</button></td><td><button className="gr-mini danger" onClick={()=>deleteGuest(g)}>Delete</button></td></tr>)}</tbody></table></div></>}

 {page==='entry'&&<><div className="gr-title"><small>GUEST INFORMATION</small><h1>Enter Guest</h1><p>One simple form for live or paper-card entry.</p></div><div className="gr-form">{[['guest_name','Name(s) *'],['address','Address'],['city','City'],['state','State'],['zip','ZIP'],['phone','Phone'],['email','Email']].map(([k,l])=><label key={k} className={k==='guest_name'||k==='address'?'wide':''}>{l}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Visit Date *<input type="date" value={form.visit_date} onChange={e=>setForm({...form,visit_date:e.target.value})}/></label><label>Guest Reception Outreach Person<select value={form.outreach_person} onChange={e=>setForm({...form,outreach_person:e.target.value})}><option value="">— Select —</option>{people.map(p=><option key={p.id} value={p.name}>{p.name}</option>)}</select></label><label>Phone Outreach Date<input type="date" value={form.phone_outreach_date} onChange={e=>setForm({...form,phone_outreach_date:e.target.value})}/></label><label className="wide">Notes / Comments<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="wide"><button className="gr-btn primary" onClick={()=>saveGuest(false)}>Save Guest</button> <button className="gr-btn" onClick={()=>saveGuest(true)}>Save & Enter Another</button></div></div></>}

 {page==='follow'&&<><div className="gr-title"><small>GUEST CARE</small><h1>Follow-Up</h1><p>One shared team queue.</p></div><div className="gr-panel gr-manage"><div><h2>Guest Reception Outreach People</h2><p>Add names once, then select them from the dropdown.</p></div><div className="gr-inline-add"><input placeholder="Add outreach person" value={newPerson} onChange={e=>setNewPerson(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addPerson()}/><button className="gr-btn primary" onClick={addPerson}>+ Add</button></div><div className="gr-chip-row">{people.map(p=><span className="gr-chip" key={p.id}>{p.name}<button onClick={()=>deletePerson(p)}>×</button></span>)}</div></div><div className="gr-panel"><table><thead><tr><th>Guest</th><th>Visit</th><th>Last Visit</th><th>Outreach Person</th><th>Status</th><th></th></tr></thead><tbody>{guests.map(g=>{const o=outreach.find(x=>x.guest_id===g.id),s=o?.phone_outreach_date?'Complete':o?.outreach_person?'Needs Outreach':'Unassigned';return <tr key={g.id}><td>{g.guest_name}</td><td>{count(g.id)>=3?'3+':count(g.id)}</td><td>{last(g.id)?.visit_date||'—'}</td><td>{o?.outreach_person||'—'}</td><td>{s}</td><td><button className="gr-mini" onClick={()=>openFollow(g)}>Open</button></td></tr>})}</tbody></table></div>{selected&&<div className="gr-modal-bg"><div className="gr-modal"><h2>{selected.guest_name}</h2><div className="gr-form compact"><label>Outreach Person<select value={follow.outreach_person||''} onChange={e=>setFollow({...follow,outreach_person:e.target.value})}><option value="">— Select —</option>{people.map(p=><option key={p.id} value={p.name}>{p.name}</option>)}</select></label><label>Phone Outreach Date<input type="date" value={follow.phone_outreach_date||''} onChange={e=>setFollow({...follow,phone_outreach_date:e.target.value})}/></label><label>Result<select value={follow.outreach_result||''} onChange={e=>setFollow({...follow,outreach_result:e.target.value})}><option value="">Select</option><option value="connected">Connected</option><option value="left_message">Left Message</option><option value="no_answer">No Answer</option><option value="follow_up_needed">Follow-Up Needed</option></select></label><label className="wide">Notes<textarea value={follow.notes||''} onChange={e=>setFollow({...follow,notes:e.target.value})}/></label></div><button className="gr-btn primary" onClick={saveFollow}>Save</button> <button className="gr-btn" onClick={()=>setSelected(null)}>Close</button></div></div>}</>}

 {page==='visits'&&<><div className="gr-title"><small>GUEST HISTORY</small><h1>Visits</h1><p>Search and record returning visits.</p></div><div className="gr-panel"><input className="gr-search" placeholder="Search name, phone, or email" value={search} onChange={e=>setSearch(e.target.value)}/><table><thead><tr><th>Guest</th><th>Visits</th><th>Last Visit</th><th>Phone</th><th>Action</th><th></th></tr></thead><tbody>{guests.filter(g=>!search||`${g.guest_name} ${g.phone||''} ${g.email||''}`.toLowerCase().includes(search.toLowerCase())).map(g=><tr key={g.id}><td><strong>{g.guest_name}</strong></td><td>{count(g.id)>=3?'3+':count(g.id)}</td><td>{last(g.id)?.visit_date||'—'}</td><td>{g.phone||'—'}</td><td><button className="gr-mini gr-visit-btn" onClick={()=>newVisit(g)}>{visitActionLabel(g)}</button></td><td><button className="gr-mini danger" onClick={()=>deleteGuest(g)}>Delete</button></td></tr>)}</tbody></table></div></>}

 {page==='inventory'&&<><div className="gr-title"><small>TEAM SUPPLIES</small><h1>Inventory</h1><p>Add, update, and remove Guest Reception supplies.</p></div><div className="gr-panel gr-manage"><h2>+ Add Inventory Item</h2><div className="gr-inventory-add"><input placeholder="Item name" value={newItem.item_name} onChange={e=>setNewItem({...newItem,item_name:e.target.value})}/><select value={newItem.category} onChange={e=>setNewItem({...newItem,category:e.target.value})}><option>Guest Materials</option><option>Welcome Items</option><option>Office Supplies</option><option>Other</option></select><input type="number" min="0" placeholder="On hand" value={newItem.quantity} onChange={e=>setNewItem({...newItem,quantity:e.target.value})}/><input type="number" min="0" placeholder="Minimum" value={newItem.minimum_quantity} onChange={e=>setNewItem({...newItem,minimum_quantity:e.target.value})}/><button className="gr-btn primary" onClick={addInventory}>Add Item</button></div></div><div className="gr-panel"><table><thead><tr><th>Item</th><th>On Hand</th><th>Minimum</th><th>Status</th><th>Actions</th></tr></thead><tbody>{inventory.map(i=><tr key={i.id}><td><strong>{i.item_name}</strong><br/><small>{i.category}</small></td><td>{i.quantity}</td><td>{i.minimum_quantity}</td><td>{i.quantity<=i.minimum_quantity?'Low Stock':'Good'}</td><td><button className="gr-mini" onClick={()=>openInventoryEdit(i)}>Update</button> <button className="gr-mini danger" onClick={()=>deleteInventory(i)}>Delete</button></td></tr>)}</tbody></table></div>{editItem&&<div className="gr-modal-bg"><div className="gr-modal"><h2>Update Inventory Item</h2><div className="gr-form compact"><label className="wide">Item Name<input value={editItem.item_name} onChange={e=>setEditItem({...editItem,item_name:e.target.value})}/></label><label>Category<select value={editItem.category||'Other'} onChange={e=>setEditItem({...editItem,category:e.target.value})}><option>Guest Materials</option><option>Welcome Items</option><option>Office Supplies</option><option>Other</option></select></label><label>Quantity On Hand<input type="number" min="0" value={editItem.quantity} onChange={e=>setEditItem({...editItem,quantity:e.target.value})}/></label><label>Minimum Quantity<input type="number" min="0" value={editItem.minimum_quantity} onChange={e=>setEditItem({...editItem,minimum_quantity:e.target.value})}/></label></div><button className="gr-btn primary" onClick={saveInventoryEdit}>Save Update</button> <button className="gr-btn" onClick={()=>setEditItem(null)}>Cancel</button></div></div>}</>}

 {page==='data'&&<><div className="gr-title"><small>DATA</small><h1>Import & Export</h1><p>Built for paper cards and Monday / Tuesday batch entry.</p></div><div className="gr-actions"><label className="gr-upload"><b>↑ Import Guest Cards</b><span>Upload CSV</span><input type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&importCSV(e.target.files[0])}/></label><button onClick={exportCSV}><b>↓ Export Guest Data</b><span>Download CSV</span></button><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['Guest Name,Address,City,State,ZIP,Phone,Email,Visit Date,Visit Number,Guest Reception Outreach Person,Phone Outreach Date,Notes\n'],{type:'text/csv'}));a.download='DLC_Guest_Template.csv';a.click()}}><b>Download CSV Template</b><span>Approved columns</span></button></div></>}
 </main></div>;
}
